spring:
  application:
    name: serviceb
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "info,health"
  info:
    env:
      enabled: true
    git:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true

info:
  app:
    name: "${spring.application.name}"
    description: "This is the Service B application"
    version: "1.0.0"
  developer:
    name: "John Doe"
    email: "john.doe@example.com"
