/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.ctrip.framework.apollo.Config;
import com.ctrip.framework.apollo.ConfigService;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.setProperty("app.id", "SampleApp");
        System.setProperty("apollo.meta", "http://localhost:8080");
        System.setProperty("env", "LOCAL");

        Config config = ConfigService.getAppConfig(); //config instance is singleton for each namespace and is never null
        String someDefaultValue = "someDefaultValueForTheKey";
        String value = config.getProperty("timeout", someDefaultValue);

        System.out.printf(value);
    }
}
