/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project6.gradle.app;

import org.apache.commons.text.WordUtils;

import static project6.gradle.app.MessageUtils.getMessage;
import static project6.gradle.utilities.StringUtils.join;
import static project6.gradle.utilities.StringUtils.split;

public class App {
    public static void main(String[] args) {
        var tokens = split(getMessage());
        var result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
