/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import io.javalin.Javalin
import io.javalin.http.Context
import java.sql.Connection
import java.sql.DriverManager

fun main() {
    connectDb()
    val app = Javalin.create()
        .get("/") { ctx: Context -> ctx.result("Hello World") }
        .get("/db") { ctx: Context -> ctx.result("Connected") }
        .start(7070)
}

fun connectDb() {
    val dbUrl = "jdbc:postgresql://db:5432/"
    val dbUser = "postgres"
    val dbPassword = "postgres"

    var connection: Connection? = null

    try {
        connection = DriverManager.getConnection(dbUrl, dbUser, dbPassword)
        connection.createStatement().use { statement ->
            val res = statement.executeQuery("SELECT version();")
            res.next()
            println(res.getString(1))
        }
        println("Connected to the database!")
    } catch (ex: Exception) {
        ex.printStackTrace()
        println("Failed to connect to the database.")
    } finally {
        connection?.close()
        println("Connection closed.")
    }

}
